//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Muhasebe
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountMovement
    {
        public int ID { get; set; }
        public int AccountID { get; set; }
        public int OwnerID { get; set; }
        public int AuthorID { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public int PaymentTypeID { get; set; }
        public decimal Value { get; set; }
        public int MovementTypeID { get; set; }
        public int ContractID { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Company Owner { get; set; }
        public virtual User Author { get; set; }
        public virtual PaymentType PaymentType { get; set; }
        public virtual AccountMovementType MovementType { get; set; }
    }
}
