//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Muhasebe
{
    using System;
    using System.Collections.Generic;
    
    public partial class BarcodeTemplate
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Path { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<int> OwnerID { get; set; }
        public Nullable<int> Width { get; set; }
        public Nullable<int> Height { get; set; }
        public Nullable<bool> IsDefault { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
