//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Muhasebe
{
    using System;
    using System.Collections.Generic;
    
    public partial class BarcodePrinter
    {
        public int ID { get; set; }
        public string Address { get; set; }
        public Nullable<int> ConnectionTypeID { get; set; }
        public Nullable<int> BarcodeTemplateID { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<int> OwnerID { get; set; }
    
        public virtual BarcodeTemplate BarcodeTemplate { get; set; }
        public virtual Company Owner { get; set; }
        public virtual ConnectionType ConnectionType { get; set; }
    }
}
