//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Muhasebe
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MicroEntities : DbContext
    {
        public MicroEntities()
            
            : base("metadata=res://*/Context.csdl|res://*/Context.ssdl|res://*/Context.msl;provider=MySql.Data.MySqlClient;provider connection string=\"server=daflan.ctmvpzo6x3ix.eu-central-1.rds.amazonaws.com;user id=mashadow;password=Thisis2ndtime?;persistsecurityinfo=True;database=muhasebe\"")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Product> Products { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<Inventory> Inventories { get; set; }
        public DbSet<Item> Items { get; set; }
        public DbSet<Company> Companies { get; set; }
        public DbSet<UnitType> UnitTypes { get; set; }
        public DbSet<Device> Devices { get; set; }
        public DbSet<DeviceType> DeviceTypes { get; set; }
        public DbSet<InvoiceNode> InvoiceNodes { get; set; }
        public DbSet<Invoice> Invoices { get; set; }
        public DbSet<PaymentType> PaymentTypes { get; set; }
        public DbSet<Income> Incomes { get; set; }
        public DbSet<IncomeType> IncomeTypes { get; set; }
        public DbSet<Expenditure> Expenditures { get; set; }
        public DbSet<ExpenditureType> ExpenditureTypes { get; set; }
        public DbSet<JobPosition> JobPositions { get; set; }
        public DbSet<Event> Events { get; set; }
        public DbSet<EventCategory> EventCategories { get; set; }
        public DbSet<PropertyReminder> PropertyReminders { get; set; }
        public DbSet<PropertyRemindingMethod> PropertyRemindingMethods { get; set; }
    }
}
