//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Muhasebe
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public int ID { get; set; }
        public Nullable<int> AuthorID { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string Description { get; set; }
        public Nullable<int> CategoryID { get; set; }
    
        public virtual User Author { get; set; }
        public virtual EventCategory Category { get; set; }
    }
}
