//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Muhasebe
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expenditure
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<int> OwnerID { get; set; }
        public Nullable<int> AuthorID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Description { get; set; }
        public Nullable<int> ExpenditureTypeID { get; set; }
        public Nullable<int> AccountID { get; set; }
        public Nullable<int> MovementID { get; set; }
    
        public virtual User Author { get; set; }
        public virtual Company Owner { get; set; }
        public virtual ExpenditureType ExpenditureType { get; set; }
        public virtual Account Account { get; set; }
    }
}
