//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Muhasebe
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public Inventory()
        {
            this.Items = new HashSet<Item>();
        }
    
        public int ID { get; set; }
        public Nullable<int> OwnerID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Address { get; set; }
    
        public virtual ICollection<Item> Items { get; set; }
        public virtual Company Owner { get; set; }
    }
}
