//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Muhasebe
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public Invoice()
        {
            this.Nodes = new HashSet<InvoiceNode>();
        }
    
        public int ID { get; set; }
        public int OwnerID { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public int AuthorID { get; set; }
        public Nullable<int> TargetID { get; set; }
        public Nullable<int> PaymentTypeID { get; set; }
        public string State { get; set; }
    
        public virtual Company Owner { get; set; }
        public virtual User Author { get; set; }
        public virtual ICollection<InvoiceNode> Nodes { get; set; }
        public virtual PaymentType PaymentType { get; set; }
    }
}
