//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Muhasebe
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceNode
    {
        public int ID { get; set; }
        public int InvoiceID { get; set; }
        public int ItemID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> BasePrice { get; set; }
        public Nullable<decimal> FinalPrice { get; set; }
        public Nullable<int> Tax { get; set; }
        public string Description { get; set; }
        public Nullable<bool> UseCustomPrice { get; set; }
    
        public virtual Invoice Invoice { get; set; }
        public virtual Item Item { get; set; }
    }
}
