//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Muhasebe
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int ID { get; set; }
        public int ProductID { get; set; }
        public int InventoryID { get; set; }
        public Nullable<int> Tax { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<decimal> BasePrice { get; set; }
        public Nullable<decimal> FinalPrice { get; set; }
        public decimal Amount { get; set; }
        public int UnitTypeID { get; set; }
        public string LocalImagePath { get; set; }
        public Nullable<int> GroupID { get; set; }
        public Nullable<decimal> TermedPrice { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Inventory Inventory { get; set; }
        public virtual UnitType UnitType { get; set; }
        public virtual ItemGroup Group { get; set; }
    }
}
