//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Muhasebe
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderNode
    {
        public int ID { get; set; }
        public int ItemID { get; set; }
        public decimal Amount { get; set; }
        public string Description { get; set; }
        public int OrderID { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Item Item { get; set; }
    }
}
