//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Muhasebe
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int ID { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> BornAt { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> LastLoginAt { get; set; }
        public string Level { get; set; }
        public string State { get; set; }
        public string Auth { get; set; }
        public Nullable<int> PositionID { get; set; }
        public Nullable<int> WorksAtID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
    
        public virtual Company WorksAt { get; set; }
        public virtual JobPosition Position { get; set; }
    }
}
